namespace Choir.Front.Laye.Syntax;

public enum SyntaxKind : ushort
{
    Invalid = 0,

    __PrintableTokenStart__ = 32,

    TokenTilde = '~',
    TokenBang = '!',
    TokenPercent = '%',
    TokenAmpersand = '&',
    TokenStar = '*',
    TokenOpenParen = '(',
    TokenCloseParen = ')',
    TokenMinus = '-',
    TokenEqual = '=',
    TokenPlus = '+',
    TokenOpenBracket = '[',
    TokenCloseBracket = ']',
    TokenOpenBrace = '{',
    TokenCloseBrace = '}',
    TokenPipe = '|',
    TokenSemiColon = ';',
    TokenColon = ':',
    TokenComma = ',',
    TokenLess = '<',
    TokenGreater = '>',
    TokenDot = '.',
    TokenSlash = '/',
    TokenQuestion = '?',
    TokenCaret = '^',
    
    __PrintableTokenEnd__ = 128,
    
    __MultiByteStart__ = 256,
    
    TokenUnknown,
    TokenEndOfFile,

    TokenIdentifier,
    TokenGlobal,

    TokenLiteralInteger,
    TokenLiteralFloat,
    TokenLiteralString,
    TokenLiteralRune,

    TokenTildeEqual,
    TokenBangEqual,
    TokenPercentEqual,
    TokenPercentColon,
    TokenPercentColonEqual,
    TokenAmpersandEqual,
    TokenStarEqual,
    TokenMinusEqual,
    TokenMinusMinus,
    TokenMinusPercent,
    TokenMinusPipe,
    TokenMinusPercentEqual,
    TokenMinusPipeEqual,
    TokenEqualEqual,
    TokenEqualGreater,
    TokenPlusEqual,
    TokenPlusPlus,
    TokenPlusPercent,
    TokenPlusPipe,
    TokenPlusPercentEqual,
    TokenPlusPipeEqual,
    TokenPipeEqual,
    TokenColonColon,
    TokenColonGreater,
    TokenColonGreaterEqual,
    TokenLessEqual,
    TokenLessLess,
    TokenLessLessEqual,
    TokenLessMinus,
    TokenLessColon,
    TokenLessEqualColon,
    TokenGreaterEqual,
    TokenGreaterGreater,
    TokenGreaterGreaterEqual,
    TokenSlashEqual,
    TokenSlashColon,
    TokenSlashColonEqual,
    TokenQuestionQuestion,
    TokenQuestionQuestionEqual,
    TokenCaretEqual,

    TokenVar,
    TokenVoid,
    TokenNoReturn,
    TokenBool,
    TokenBoolSized,
    TokenInt,
    TokenIntSized,
    TokenFloatSized,

    TokenTrue,
    TokenFalse,
    TokenNil,

    TokenIf,
    TokenElse,
    TokenFor,
    TokenWhile,
    TokenDo,
    TokenSwitch,
    TokenCase,
    TokenDefault,
    TokenReturn,
    TokenBreak,
    TokenContinue,
    TokenFallthrough,
    TokenYield,
    TokenUnreachable,

    TokenDefer,
    TokenDiscard,
    TokenGoto,
    TokenXyzzy,
    TokenAssert,
    TokenTry,
    TokenCatch,

    TokenStruct,
    TokenVariant,
    TokenEnum,
    //TokenStrict,
    TokenTemplate,
    TokenAlias,
    TokenTest,
    TokenImport,
    TokenExport,
    //TokenFrom,
    //TokenAs,
    TokenOperator,

    TokenMut,
    TokenNew,
    TokenDelete,
    TokenCast,
    TokenIs,
    
    TokenSizeof,
    TokenAlignof,
    TokenOffsetof,

    TokenNot,
    TokenAnd,
    TokenOr,
    TokenXor,

    TokenVarargs,
    TokenConst,
    TokenForeign,
    TokenInline,
    TokenCallconv,
    TokenPure,
    TokenDiscardable,
}
