= The Choir Compiler Project

This repository contains the source code for the Choir, a compiler project primarily for the Laye programming language.

The Choir compiler project depends on https://github.com/nashiora/llvm-project[LLVM].
For the time being, you'll need to set up and build a copy yourself for Choir's build process to reference.

== Getting and Building Choir

NOTE: If you're building on Windows, all steps assume you're using the appropriate developer command prompt or a terminal instance configured correctly to mimick it. For Visual Studio 2022, search for `x64 Native Tools Command Prompt for VS 2022`. Adapt this for your installation, and *make sure* it's the 64-bit tools. Invoking `vcvars64.bat` or `vcvarsall.bat x64` *should* be identical, but your mileage may vary with MSVC.

As a prerequisite for building Choir, you'll need LLVM development binaries. There is currently a dependence on LLVM's CMake build files which are not provided by official/community releases. So, for as long as that's the case you'll have to build LLVM yourself to have access to the required CMake files.

First, follow the Getting Started instructions provided with https://github.com/nashiora/llvm-project[LLVM] and ensure you can build it in your environment. We recommend building LLVM using something similar to either of the two following CMake commands, from the root of the LLVM repository. Ensure you're following LLVM's Getting Started guide for your system, and replace only the CMake command step.

On Windows using Visual Studio/MSVC (assuming Visual Studio 2022):
----
cmake -S llvm -B build -G "Visual Studio 17 2022" -A x64 -Thost=x64 -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra' -DLLVM_ENABLE_UNWIND_TABLES=OFF -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_UNREACHABLE_OPTIMIZE=OFF -DLLVM_ENABLE_DUMP=ON -DLLVM_CCACHE_BUILD=ON -DLLVM_ENABLE_DOXYGEN=ON -DLLVM_ENABLE_FFI=ON -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF
----

On Windows/Linux using Ninja:
----
cmake -S llvm -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra' -DLLVM_C_COMPILER=clang -DLLVM_CXX_COMPILER=clang++ -DLLVM_ENABLE_UNWIND_TABLES=OFF -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_UNREACHABLE_OPTIMIZE=OFF -DLLVM_ENABLE_DUMP=ON -DLLVM_CCACHE_BUILD=ON -DLLVM_ENABLE_DOXYGEN=ON -DLLVM_ENABLE_FFI=ON -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF
----

****
[discrete]
==== Using Ninja on Windows

Building LLVM with the Ninja generator on Windows, or linking with existing Windows binaries, will likely require an additional step before the Choir project can be built against it.

Unless you're already using Visual Studio 2019 Professional, you'll need to find the DIA SDK in your Visual Studio install and copy its contents to a facade 2019 Professional installation directory. You should be able to do the following to prevent link errors using the Ninja generator:

----
mkdir -p "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional"

# if professional vs 2022

cp -rv "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/DIA SDK" "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/DIA SDK"

# if community vs 2022

cp -rv "C:/Program Files/Microsoft Visual Studio/2022/Community/DIA SDK" "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/DIA SDK"
----
****

=== Building Choir on Windows

When building Choir on Windows, either the Visual Studio or Ninja generators can be used. The note in the previous section on building LLVM where the Ninja generator is not recommended only applies to the LLVM project, not to Choir. A Ninja build of Choir referencing LLVM binaries built using the Visual Studio 2022 generator will still work if you prefer that workflow.

==== Using Visual Studio / MSVC

There are two options for using Visual Studio / MSVC with this project:

. Use Visual Studio to manage configuring and building with CMake for you.
    .. Open the root folder of this repository in Visual Studio. CMake projects are supported out of the box if you installed with that feature enabled, so you can configure and build without touching the command.
        - Once in Visual Studio, navigate to `Project > CMake Settings for Choir` and include `-DCHOIR_LLVM_REDIST_DIR=<Path to LLVM binaries>` in the `Command arguments > CMake command arguments` section. Ideally you use an absolute path. If you used the Visual Studio 2022 generator to build LLVM as suggested, or have compatible binaries, then that path should end with something akin to `llvm-project\build\Debug\`, a directory which should contain both a `bin` and `lib` directory.
        - By default, Choir will attempt to find LLVM's development CMake files adjacent to the directory you provided for `CHOIR_LLVM_REDIST_DIR`, at `..\lib\cmake\` specifically. If this directory does not exist, CMake will issue an error telling you so and you'll have to manually provide `CHOIR_LLVM_CMAKE_DIR` in the same manner.
    .. Configure the project.
        - If you don't know what hotkeys do that for you, use `Project > Configure Cache`.
    .. Build the Choir project.
        - You may need to select `choir.exe` from the "Startup Item" dropdown (the one with the green "play" button) in order to get the correct options to build the project. If so, `Build > choir.exe` should exist. 
        - Alternatively, use the `Build > Build all` option so you don't have to find the specific project itself.
. Configure using the Visual Studio 2022 generator from the terminal.
    .. From the project root, configure the project with `cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -Thost=x64`.
    .. Build the project 
        - You can then open the generated `build\Choir.sln` file in Visual Studio 2022 and build either the `choir` project or the entire solution, but you shouldn't expect to be able to add or remove files from within Visual Studio.
        - Alternatively, you can use CMake or MSBuild from the terminal. Either `cmake --build build` or `msbuild build\Choir.sln` should do the trick.

==== Using Ninja
