namespace Choir.FrontEnd.Score.Syntax;

public enum ScoreTokenKind
    : ushort
{
    Invalid = 0,

    Bang = '!',
    Pound = '#',
    Dollar = '$',
    Percent = '%',
    Ampersand = '&',
    LeftParen = '(',
    RightParen = ')',
    Star = '*',
    Plus = '+',
    Comma = ',',
    Minus = '-',
    Dot = '.',
    Slash = '/',
    Colon = ':',
    SemiColon = ';',
    Less = '<',
    Equal = '=',
    Greater = '>',
    Question = '?',
    At = '@',
    OpenSquare = '[',
    BackSlash = '\\',
    CloseSquare = ']',
    Caret = '^',
    Underscore = '_',
    Backtick = '`',
    OpenCurly = '{',
    Pipe = '|',
    CloseCurly = '}',
    Tilde = '~',

    EndOfFile = 256,
    UnexpectedCharacter,

    BangEqual,
    PercentEqual,
    AmpersandEqual,
    AmpersandAmpersand,
    StarEqual,
    PlusEqual,
    MinusEqual,
    DotDot,
    SlashEqual,
    ColonColon,
    LessEqual,
    LessEqualGreater,
    LessLess,
    LessLessEqual,
    EqualEqual,
    GreaterEqual,
    GreaterGreater,
    GreaterGreaterEqual,
    PipeEqual,
    TildeEqual,

    Identifier,

    Func,
    Let,
    Const,
    Struct,
    Variant,
    Union,
    Enum,
    Alias,

    Module,
    Export,
    Import,

    True,
    False,
    Nil,
    This,

    If,
    Else,
    While,
    For,
    Do,
    Switch,
    Case,
    Default,

    Return,
    Break,
    Continue,
    Goto,
    Yield,
}
